### ISSUE TITLE
Failed to activate the webbox-color package

### ISSUE THREAD

**Issue by lx9203** [webBoxio/atom-color#58]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [webbox-color](https://github.com/webBoxio/atom-color) package 0.5.9

### Stack Trace

Failed to activate the webbox-color package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/webbox-color/lib/color.coffee:1:29)
    at /packages/webbox-color/lib/color.coffee:1:1)
    at /packages/webbox-color/lib/color.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:641362)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3029314)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017448)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017226)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017086)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017029)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382643)
    at config.transactAsync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382259)
    at Config.transactAsync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:332443)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382209)
    at PackageManager.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:381827)
    at t.loadState.then (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:662772)
    at <anonymous>
```

### Commands

```
     -9:42.1.0 core:backspace (input.hidden-input)
     -9:39.5.0 core:confirm (input.hidden-input)
     -9:35.7.0 core:paste (input.hidden-input)
  2x -9:31.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
atom-beautify 0.33.4 
atom-css-comb 3.5.1 
atom-live-server 2.3.0 
atom-ternjs 0.18.5 
busy-signal 2.0.0 
color-picker 2.3.0 
column-select 1.0.1 
css-color-name 0.4.0 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.30 
highlight-line 0.12.0 
highlight-selected 0.14.0 
html-to-css 0.2.2 
indent-guide-improved 1.4.13 
intentions 1.1.5 
linter 2.3.0 
linter-csslint 2.0.5 
linter-eslint 8.5.2 
linter-htmlhint 1.6.0 
linter-sass-lint 1.9.0 
linter-stylelint 4.4.3 
linter-tidy 2.4.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
swackets 0.35.0 
webbox-color 0.5.9 
```

**Comment by lx9203** [comment]
help
